apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-service
spec:
  selector:
    matchLabels:
      app: producer-service
  template:
    metadata:
      labels:
        app: producer-service
    spec:
      containers:
      - name: producer-service
        image: trekkerone/producer-service:latest
        env:
        - name: RABBITMQ_HOST
          value: "localhost"
        - name: RABBITMQ_PORT
          value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: producer-service
spec:
  type: NodePort
  selector:
    app: producer-service
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31500


